[package]
name = "canary"
version = "0.12.0"
authors = ["Anders Jensen <anders.c.jensen@gmail.com>"]
edition = "2018"

[dependencies]
#actix-rt = "1.1"
actix-web = "3"
log = "0.4"
env_logger = "0.8"

[profile.release]
lto = true