[package]
name = "canary"
version = "0.10.0"
authors = ["Anders Jensen <anders.c.jensen@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
log = "0.4"
env_logger = "0.6"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false